services:
  web-dbt:
    image: obnoxieux/web-dbt:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-dbt.rule=Host(`obnx.dev`)"
      - "traefik.http.routers.web-dbt.entrypoints=websecure"
      - "traefik.http.routers.web-dbt.tls.certresolver=letsEncrypt"

networks:
  proxy:
    external: true